### ISSUE TITLE
PushNotificationChannelManager.CreatePushNotificationChannelForApplicationAsync() exception

### ISSUE THREAD

**Issue by mohammedagha-1** [MicrosoftDocs/winrt-api#1829]
PushNotificationChannelManager.CreatePushNotificationChannelForApplicationAsync() throw 
Value does not fall within the expected range.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Sita.Notification.WindowsRegistration.RegistrationPage.<RegisterBackgroundTask>d__2.MoveNext() in 
D:\Workspaces\SIta\Sita.Notifications\src\Desktop\Sita.Notification.WindowsRegistration\Sita.Notification.WindowsRegistration\RegistrationPage.cs:line 55

What is the cause for this problem?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 455350f6-3f93-0845-134e-23f8355e74dd
* Version Independent ID: 860fee99-e126-6e65-53a4-531e9c4ff2de
* Content: [PushNotificationChannelManager.CreatePushNotificationChannelForApplicationAsync Method (Windows.Networking.PushNotifications) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.networking.pushnotifications.pushnotificationchannelmanager.createpushnotificationchannelforapplicationasync?view=winrt-19041)
* Content Source: [winrt-api-build/xml/Windows.Networking.PushNotifications/PushNotificationChannelManager.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Networking.PushNotifications/PushNotificationChannelManager.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by mohammedagha-1** [comment]
I restarted my laptop and the exception is disappeared
