### ISSUE TITLE
ApplicationView.GetForCurrentView throws

### ISSUE THREAD

**Issue by cmalonzo** [MicrosoftDocs/winrt-api#1949]
Following these [instructions](https://docs.microsoft.com/en-us/microsoft-edge/webview2/gettingstarted/winui), I set up a WinUI 3 Blank App Packaged (WinUI for Desktop). I am running 

I have a button in my MainWindow that I want to toggle CompactOverlay:

```
    public sealed partial class MainWindow : Window
    {
        private bool _compactOverlayEnabled = false;

        public MainWindow()
        {
            this.InitializeComponent();
        }

        private async void ToggleCompactOverlay(object sender, RoutedEventArgs e)
        {
            var currentView = ApplicationView.GetForCurrentView();
            await currentView.TryEnterViewModeAsync(ApplicationViewMode.CompactOverlay);
        }
    }
```

However, when `currentView = ApplicationView.GetForCurrentView();` is called, the app throws the following exception:

```
Element not found. (0x80070490)
   at WinRT.ExceptionHelpers.ThrowExceptionForHR(Int32 hr)
   at ABI.Windows.UI.ViewManagement.IApplicationViewStatics2.global::Windows.UI.ViewManagement.IApplicationViewStatics2.GetForCurrentView()
   at Windows.UI.ViewManagement.ApplicationView.GetForCurrentView()
   at StickyNotes_WinUI.MainWindow.<ToggleCompactOverlay>d__2.MoveNext() in C:\dev\SampleApp\SampleApp\SampleApp\MainWindow.xaml.cs:line 37
```

I'm also quite new to using WinUI3 but otherwise I can't find any resources online that otherwise tells me I can't call ApplicationView.GetForCurrentView() when I click a button. The call is not being made in the constructor, for example.

**Comment by jaigak** [comment]
WinUI 3 in desktop mode doesn't support GetForCurrentView methods yet. See https://docs.microsoft.com/en-us/windows/apps/winui/winui3/#corewindow-applicationview-coreapplicationview-and-coredispatcher-in-desktop-apps

**Comment by cmalonzo** [comment]
> WinUI 3 in desktop mode doesn't support GetForCurrentView methods yet. See https://docs.microsoft.com/en-us/windows/apps/winui/winui3/#corewindow-applicationview-coreapplicationview-and-coredispatcher-in-desktop-apps

Thanks @Jaiganeshkumaran. What I'm trying to do is achieve a compact overlay with my window. Is there guidance on how to do this with WinUi3?

**Comment by Karl-Bridge-Microsoft** [comment]
@marb2000 - Is this something you can help with?

**Comment by jwmsft** [comment]
Current guidance for CompactOverlay in WinUI 3 is at https://learn.microsoft.com/en-us/windows/apps/develop/ui-input/manage-app-windows#the-appwindowpresenter-class-and-subclasses
